export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as GamePage } from './Game'
export { default as Create } from './Create'
export { default as Join } from './Join'
export { default as Lobby } from './Lobby'
export { default as Home } from './Home'
export { default as Scoreboard } from './Scoreboard'
